name: CI

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  conflicts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Merge Conflict finder
        uses: olivernybroe/action-conflict-finder@v4.0

  unit:
    needs: [conflicts]

    runs-on: ubuntu-latest

    services:
        postgres:
            image: postgres:12
            env:
                POSTGRES_DB: foundation_test_db
                POSTGRES_USER: foundation_test_db
                POSTGRES_PASSWORD: password
            ports:
                - 5432:5432
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, dom, fileinfo, intl, gd, imagick, bcmath, soap, zip, sqlite, pcov
          coverage: pcov

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Authenticate Nova
        run: composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_LICENSE_KEY }}

      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist --optimize-autoloader --ignore-platform-reqs

      - name: Run Tests
        run: composer test
        env:
            DB_CONNECTION: pgsql
            DB_HOST: 127.0.0.1
            DB_PORT: 5432
            DB_DATABASE: foundation_test_db
            DB_USERNAME: foundation_test_db
            DB_PASSWORD: password
            PDO_ATTR_PERSISTENT: false
