name: Compress

on:
  pull_request:
    paths:
      - "**.svg"

jobs:
  svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Optimize SVGs
        uses: ericcornelissen/svgo-action@v4.0.9
        id: svgo
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          svgo-config: .svgo.js

      - name: Commit optimizations
        uses: stefanzweifel/git-auto-commit-action@v7
        if: ${{steps.svgo.outputs.DID_OPTIMIZE}}
        with:
          commit_message: Optimize ${{steps.svgo.outputs.OPTIMIZED_COUNT}} SVG(s)
